
//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct AccessToken: Codable, Equatable {
    private enum CodingKeys: String, CodingKey {
        case token
    }

    /** アクセストークン */
    public let token: String

    public init(token: String) {
        self.token = token
    }
}
