
//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct ServerError: Codable, Equatable {
    private enum CodingKeys: String, CodingKey {
        case code
        case message
        case title
    }

    /** エラーコード */
    public let code: Int

    /** エラー表示メッセージ */
    public let message: String

    /** エラー表示タイトル */
    public let title: String

    public init(code: Int, message: String, title: String) {
        self.code = code
        self.message = message
        self.title = title
    }
}
