
//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct User: Codable, Equatable {
    private enum CodingKeys: String, CodingKey {
        case createdAt = "created_at"
        case email
        case loggedInAt = "logged_in_at"
        case uuid
    }

    /** アカウント作成日時 */
    public let createdAt: DateTime

    /** ユーザーE-mail */
    public let email: String

    /** 最終ログイン日時 */
    public let loggedInAt: DateTime

    /** ユーザーID */
    public let uuid: ID

    public init(createdAt: DateTime, email: String, loggedInAt: DateTime, uuid: ID) {
        self.createdAt = createdAt
        self.email = email
        self.loggedInAt = loggedInAt
        self.uuid = uuid
    }
}
