
//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation
import Moya

public extension Endpoint.Authorization {
    /** ログイン */

    struct PostLogin: MockAPITargetType {
        public typealias Response = AccessToken

        public var method: Moya.Method {
            Moya.Method(rawValue: "POST")
        }

        public var path: String {
            let path = "/login"
            return path
        }

        public var task: Task {
            .requestJSONEncodable(body)
        }

        public var body: Credential

        public init(body: Credential) {
            self.body = body
        }
    }
}
