
//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation
import Moya

/** API for Mock */
public enum Endpoint {
    public enum Authorization {}
    public enum Me {}
}
