
//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation
import Moya

public protocol MockAPIBaseTargetType: TargetType {
    associatedtype Response
}

public extension MockAPIBaseTargetType {
    var baseURL: URL {
        URL(string: "http://127.0.0.1:3200")!
    }

    var headers: [String: String]? {
        nil
    }

    var sampleData: Data {
        Data()
    }

    var validationType: ValidationType {
        .successCodes
    }
}

public protocol MockAPITargetType: MockAPIBaseTargetType {}
