
//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct NoContent: Codable {
    public init() {}
}

public extension NoContent {
    init(from _: Decoder) throws {
        self.init()
    }
}
